//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsAppStudio.Convert.Xamarin {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ConvertResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ConvertResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WindowsAppStudio.Convert.Xamarin.ConvertResources", typeof(ConvertResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .W10.
        /// </summary>
        internal static string AppStudioPathExtension {
            get {
                return ResourceManager.GetString("AppStudioPathExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section.
        /// </summary>
        internal static string AppStudioSectionEndingFilename {
            get {
                return ResourceManager.GetString("AppStudioSectionEndingFilename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Section.
        /// </summary>
        internal static string AppStudioSectionFileIgnore {
            get {
                return ResourceManager.GetString("AppStudioSectionFileIgnore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sections.
        /// </summary>
        internal static string AppStudioSectionsDirectory {
            get {
                return ResourceManager.GetString("AppStudioSectionsDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to copied.
        /// </summary>
        internal static string Copied {
            get {
                return ResourceManager.GetString("Copied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to : the files for the collection &quot;{0}&quot; are already updated.
        ///.
        /// </summary>
        internal static string ErrorCollectionAlreadyUpdated {
            get {
                return ResourceManager.GetString("ErrorCollectionAlreadyUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: no Windows App Studio app found in the source directory..
        /// </summary>
        internal static string ErrorFindingApp {
            get {
                return ResourceManager.GetString("ErrorFindingApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: no section found with the name file &quot;{0}&quot;.
        ///.
        /// </summary>
        internal static string ErrorFindingSection {
            get {
                return ResourceManager.GetString("ErrorFindingSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: no section found in the source directory..
        /// </summary>
        internal static string ErrorFindingSections {
            get {
                return ResourceManager.GetString("ErrorFindingSections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error. &quot;{0}&quot; file was not successfully {1}.
        ///.
        /// </summary>
        internal static string ErrorInstallFile {
            get {
                return ResourceManager.GetString("ErrorInstallFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: nothing to do!! (WithBase and WithCollections are false).
        /// </summary>
        internal static string ErrorNothingToDo {
            get {
                return ResourceManager.GetString("ErrorNothingToDo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Xamarin folder already exists..
        /// </summary>
        internal static string ErrorXamarinFolderAlreadyExists {
            get {
                return ResourceManager.GetString("ErrorXamarinFolderAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fatal error.
        ///.
        /// </summary>
        internal static string FatalErrorInstallFile {
            get {
                return ResourceManager.GetString("FatalErrorInstallFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to modified.
        /// </summary>
        internal static string Modified {
            get {
                return ResourceManager.GetString("Modified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ////////////////////////////////////////
        ///// Modified by Was2Xamarin  //
        ///////////////////////////////////////////
        ///// Was2Xamarin              //
        ///// Created by Hervé PHILIPPE          //
        ///// alchiweb@live.fr / alchiweb.fr     //
        ///////////////////////////////////////////
        ///.
        /// </summary>
        internal static string ReplaceAlchiwebModified {
            get {
                return ResourceManager.GetString("ReplaceAlchiwebModified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success! All base files were successfully modified.
        ///.
        /// </summary>
        internal static string SuccessBaseInstall {
            get {
                return ResourceManager.GetString("SuccessBaseInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success! All files for the collection &quot;{0}&quot; were successfully modified.
        ///.
        /// </summary>
        internal static string SuccessCollectionInstall {
            get {
                return ResourceManager.GetString("SuccessCollectionInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .Xamarin.
        /// </summary>
        internal static string XamarinPathExtension {
            get {
                return ResourceManager.GetString("XamarinPathExtension", resourceCulture);
            }
        }
    }
}
