//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WasAppNamespace.Strings {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WasAppNamespace.Strings.Resources", typeof(Resources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows App Studio Libraries.
        /// </summary>
        internal static string AboutAppStudioOpenSourceLibraries_Content {
            get {
                return ResourceManager.GetString("AboutAppStudioOpenSourceLibraries.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about.
        /// </summary>
        internal static string AboutButton_Label {
            get {
                return ResourceManager.GetString("AboutButton.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Insights.
        /// </summary>
        internal static string AboutCapabilityApplicationInsights_Text {
            get {
                return ResourceManager.GetString("AboutCapabilityApplicationInsights.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internet connection.
        /// </summary>
        internal static string AboutCapabilityInternet_Text {
            get {
                return ResourceManager.GetString("AboutCapabilityInternet.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tile Updater.
        /// </summary>
        internal static string AboutCapabilityTileUpdater_Text {
            get {
                return ResourceManager.GetString("AboutCapabilityTileUpdater.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string AboutFlyout_Title {
            get {
                return ResourceManager.GetString("AboutFlyout.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Powered by.
        /// </summary>
        internal static string AboutPoweredBy_Text {
            get {
                return ResourceManager.GetString("AboutPoweredBy.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about.
        /// </summary>
        internal static string AboutSection_Text {
            get {
                return ResourceManager.GetString("AboutSection.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application capabilities.
        /// </summary>
        internal static string AboutSectionCapabilities_Text {
            get {
                return ResourceManager.GetString("AboutSectionCapabilities.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dependencies.
        /// </summary>
        internal static string AboutSectionLicenses_Text {
            get {
                return ResourceManager.GetString("AboutSectionLicenses.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This app is developed using following open source software:.
        /// </summary>
        internal static string AboutSectionLicensesDescription_Text {
            get {
                return ResourceManager.GetString("AboutSectionLicensesDescription.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View more information.
        /// </summary>
        internal static string AboutViewMoreInformation_Content {
            get {
                return ResourceManager.GetString("AboutViewMoreInformation.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advertisement.
        /// </summary>
        internal static string AdvertisementSection_Header {
            get {
                return ResourceManager.GetString("AdvertisementSection.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App version:.
        /// </summary>
        internal static string AppVersion_Text {
            get {
                return ResourceManager.GetString("AppVersion.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press to set big size on text.
        /// </summary>
        internal static string BigTextButton_AutomationProperties_Name {
            get {
                return ResourceManager.GetString("BigTextButton.AutomationProperties.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to big text.
        /// </summary>
        internal static string BigTextButton_Label {
            get {
                return ResourceManager.GetString("BigTextButton.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Developed by:.
        /// </summary>
        internal static string DevelopedBy_Text {
            get {
                return ResourceManager.GetString("DevelopedBy.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add or remove to favorites.
        /// </summary>
        internal static string FavoriteButton_AutomationProperties_Name {
            get {
                return ResourceManager.GetString("FavoriteButton.AutomationProperties.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorite.
        /// </summary>
        internal static string FavoriteButton_Label {
            get {
                return ResourceManager.GetString("FavoriteButton.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press to start full screen mode.
        /// </summary>
        internal static string FullScreenButton_AutomationProperties_Name {
            get {
                return ResourceManager.GetString("FullScreenButton.AutomationProperties.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Screen.
        /// </summary>
        internal static string FullScreenButton_Label {
            get {
                return ResourceManager.GetString("FullScreenButton.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last update.
        /// </summary>
        internal static string LastUpdated_Text {
            get {
                return ResourceManager.GetString("LastUpdated.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an unexpected error loading the section data. Try to refresh later..
        /// </summary>
        internal static string ListErrorNotificationControl_ErrorText {
            get {
                return ResourceManager.GetString("ListErrorNotificationControl.ErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an unexpected error loading the section data. Try to refresh later..
        /// </summary>
        internal static string LoadDataErrorMessage_Text {
            get {
                return ResourceManager.GetString("LoadDataErrorMessage.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        internal static string LoadingRelatedContent {
            get {
                return ResourceManager.GetString("LoadingRelatedContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load more.
        /// </summary>
        internal static string LoadMoreButton_Content {
            get {
                return ResourceManager.GetString("LoadMoreButton.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press to load more items.
        /// </summary>
        internal static string LoadMoreItemsButton_AutomationPropertiesName {
            get {
                return ResourceManager.GetString("LoadMoreItemsButton.AutomationPropertiesName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load more items.
        /// </summary>
        internal static string LoadMoreItemsButton_Label {
            get {
                return ResourceManager.GetString("LoadMoreItemsButton.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to subtitle.
        /// </summary>
        internal static string NarrationSubTitle {
            get {
                return ResourceManager.GetString("NarrationSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to title.
        /// </summary>
        internal static string NarrationTitle {
            get {
                return ResourceManager.GetString("NarrationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application navigation panel.
        /// </summary>
        internal static string NavigationPageButton_AutomationProperties_Name {
            get {
                return ResourceManager.GetString("NavigationPageButton.AutomationProperties.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string NavigationPaneAbout {
            get {
                return ResourceManager.GetString("NavigationPaneAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy terms.
        /// </summary>
        internal static string NavigationPanePrivacy {
            get {
                return ResourceManager.GetString("NavigationPanePrivacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The video cannot be shown because there is no connection available..
        /// </summary>
        internal static string NoConnectionAvailable_Text {
            get {
                return ResourceManager.GetString("NoConnectionAvailable.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Looks that there is nothing here. Navigate through the application and add your items hear by tapping or clicking in the icon.
        /// </summary>
        internal static string NoFavoritesTxt_Text {
            get {
                return ResourceManager.GetString("NoFavoritesTxt.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press to set normal size on text.
        /// </summary>
        internal static string NormalTextButton_AutomationProperties_Name {
            get {
                return ResourceManager.GetString("NormalTextButton.AutomationProperties.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to normal text.
        /// </summary>
        internal static string NormalTextButton_Label {
            get {
                return ResourceManager.GetString("NormalTextButton.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to privacy.
        /// </summary>
        internal static string PrivacyButton_Label {
            get {
                return ResourceManager.GetString("PrivacyButton.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy.
        /// </summary>
        internal static string PrivacyFlyout_Title {
            get {
                return ResourceManager.GetString("PrivacyFlyout.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy terms.
        /// </summary>
        internal static string PrivacyTermsButton_Content {
            get {
                return ResourceManager.GetString("PrivacyTermsButton.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press to refresh the data.
        /// </summary>
        internal static string RefreshButton_AutomationPropertiesName {
            get {
                return ResourceManager.GetString("RefreshButton.AutomationPropertiesName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to refresh.
        /// </summary>
        internal static string RefreshButton_Label {
            get {
                return ResourceManager.GetString("RefreshButton.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roaming is not enabled in this device. Data stored on this device will not be replicated in the rest of your devices..
        /// </summary>
        internal static string RoamingWarning_Text {
            get {
                return ResourceManager.GetString("RoamingWarning.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to type search text....
        /// </summary>
        internal static string SearchBox_PlaceholderText {
            get {
                return ResourceManager.GetString("SearchBox.PlaceholderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No results found..
        /// </summary>
        internal static string SearchNoResultsTxt_Text {
            get {
                return ResourceManager.GetString("SearchNoResultsTxt.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search results for:.
        /// </summary>
        internal static string SearchResultTxt_Text {
            get {
                return ResourceManager.GetString("SearchResultTxt.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an unexpected error loading the section data. Try to refresh later..
        /// </summary>
        internal static string SectionListItem_ErrorText {
            get {
                return ResourceManager.GetString("SectionListItem.ErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View all.
        /// </summary>
        internal static string SectionListItem_HeaderLinkText {
            get {
                return ResourceManager.GetString("SectionListItem.HeaderLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press to share.
        /// </summary>
        internal static string ShareItemButton_AutomationProperties_Name {
            get {
                return ResourceManager.GetString("ShareItemButton.AutomationProperties.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to share.
        /// </summary>
        internal static string ShareItemButton_Label {
            get {
                return ResourceManager.GetString("ShareItemButton.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press to show or hide information.
        /// </summary>
        internal static string ShowInfoButton_AutomationProperties_Name {
            get {
                return ResourceManager.GetString("ShowInfoButton.AutomationProperties.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show info.
        /// </summary>
        internal static string ShowInfoButton_Label {
            get {
                return ResourceManager.GetString("ShowInfoButton.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press to start media presentation.
        /// </summary>
        internal static string ShowPresentationButton_AutomationProperties_Name {
            get {
                return ResourceManager.GetString("ShowPresentationButton.AutomationProperties.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slide show.
        /// </summary>
        internal static string ShowPresentationButton_Label {
            get {
                return ResourceManager.GetString("ShowPresentationButton.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press to set small size on text.
        /// </summary>
        internal static string SmallTextButton_AutomationProperties_Name {
            get {
                return ResourceManager.GetString("SmallTextButton.AutomationProperties.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to small text.
        /// </summary>
        internal static string SmallTextButton_Label {
            get {
                return ResourceManager.GetString("SmallTextButton.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no related content..
        /// </summary>
        internal static string ThereIsNotRelatedContent {
            get {
                return ResourceManager.GetString("ThereIsNotRelatedContent", resourceCulture);
            }
        }
    }
}
